name: dio_cache_interceptor_hive_store_example
description: dio_cache_interceptor_hive_store example.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
