name: dio_cache_interceptor_objectbox_store
description: A DB cache store implementation with ObjectBox for dio_cache_interceptor package.
version: 0.0.2
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_objectbox_store

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio_cache_interceptor: ^3.0.3
  objectbox: ^1.2.0

dev_dependencies:
  build_runner: ^2.1.4
  objectbox_generator: any
  # https://pub.dev/packages/lints
  lints: ^1.0.1
  # https://pub.dev/packages/test
  test: ^1.18.0